<?php

namespace App\Http\Controllers;

use App\Models\Bill;
use App\Models\Customer;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function dashboard(Request $request)
    {


        $isFiltered = $request->filled('from_date') || $request->filled('to_date');


        $fromDate = $request->query('from_date', now()->format('Y-m-d'));
        $toDate = $request->query('to_date', now()->format('Y-m-d'));

        /*
        |--------------------------------------------------------------------------
        | Validation
        |--------------------------------------------------------------------------
        */

        $request->validate([
            'from_date' => [
                'nullable',
                'date',
            ],

            'to_date' => [
                'nullable',
                'date',
                'after_or_equal:from_date',
            ],
        ], [
            'from_date.date' => 'શરૂઆતની તારીખ માન્ય નથી.',

            'to_date.date' => 'અંતિમ તારીખ માન્ય નથી.',

            'to_date.after_or_equal' =>
                'અંતિમ તારીખ શરૂઆતની તારીખ કરતા નાની હોઈ શકે નહીં.',
        ]);

        /*
        |--------------------------------------------------------------------------
        | Dashboard Cards
        |--------------------------------------------------------------------------
        */

        if ($isFiltered) {

    // -------------------------------------------------
    // FILTERED DATA
    // -------------------------------------------------

    $startDateTime = $fromDate . ' 00:00:00';
    $endDateTime = $toDate . ' 23:59:59';

    // Selected date range sales
    $todaysSales = Bill::whereBetween('created_at', [
        $startDateTime,
        $endDateTime
    ])->sum('grand_total');

    // Selected date range bills
    $todaysBillCount = Bill::whereBetween('created_at', [
        $startDateTime,
        $endDateTime
    ])->count();

    // -------------------------------------------------
    // FILTERED DUE
    // -------------------------------------------------

    $filteredBills = Bill::whereBetween('created_at', [
        $startDateTime,
        $endDateTime
    ])->get();

    $totalDue = 0;

    foreach ($filteredBills as $bill) {

        // Due generated by this bill
        $billDue = (float) $bill->grand_total
                 - (float) $bill->due_paid_now;

        // Do not allow negative due
        if ($billDue > 0) {
            $totalDue += $billDue;
        }
    }

    // Customers in selected date range
    $totalCustomers = Bill::whereBetween('created_at', [
        $startDateTime,
        $endDateTime
    ])
        ->whereNotNull('customer_id')
        ->distinct('customer_id')
        ->count('customer_id');

} else {

    // -------------------------------------------------
    // NORMAL DASHBOARD = TODAY
    // -------------------------------------------------

    $today = now()->format('Y-m-d');

    // Today's sales
    $todaysSales = Bill::whereDate('created_at', $today)
        ->sum('grand_total');

    // Today's bills
    $todaysBillCount = Bill::whereDate('created_at', $today)
        ->count();

    // Current total outstanding due
    $totalDue = Customer::sum('balance_due');

    // Today's customers
    $totalCustomers = Bill::whereDate('created_at', $today)
        ->whereNotNull('customer_id')
        ->distinct('customer_id')
        ->count('customer_id');

    $fromDate = $today;
    $toDate = $today;
}


        /*
        |--------------------------------------------------------------------------
        | Year selector for monthly chart
        |--------------------------------------------------------------------------
        */

        $selectedYear = (int) $request->query(
            'year',
            now()->year
        );

        $availableYears = Bill::selectRaw(
            'DISTINCT YEAR(created_at) as year'
        )
            ->pluck('year')
            ->push(now()->year)
            ->unique()
            ->sortDesc()
            ->values();


        /*
        |--------------------------------------------------------------------------
        | Monthly Sales Chart
        |--------------------------------------------------------------------------
        */

        $monthlyTotalsRaw = Bill::selectRaw(
            'MONTH(created_at) as month, SUM(grand_total) as total'
        )
            ->whereYear('created_at', $selectedYear)
            ->groupBy('month')
            ->pluck('total', 'month');

        $monthlyTotals = [];

        for ($m = 1; $m <= 12; $m++) {
            $monthlyTotals[] = (float) (
                $monthlyTotalsRaw[$m] ?? 0
            );
        }


        /*
        |--------------------------------------------------------------------------
        | Cash vs Due
        |--------------------------------------------------------------------------
        */

        $cashTotal = Bill::where(
            'payment_type',
            'cash'
        )->sum('grand_total');

        $dueTotal = Bill::where(
            'payment_type',
            'due'
        )->sum('grand_total');

        $cashDueGrandTotal = $cashTotal + $dueTotal;

        $cashPercent = $cashDueGrandTotal > 0
            ? round(
                ($cashTotal / $cashDueGrandTotal) * 100
            )
            : 0;

        $duePercent = $cashDueGrandTotal > 0
            ? round(
                ($dueTotal / $cashDueGrandTotal) * 100
            )
            : 0;


        /*
        |--------------------------------------------------------------------------
        | Recent Bills
        |--------------------------------------------------------------------------
        */

        $recentBills = Bill::with('customer')
            ->latest()
            ->limit(4)
            ->get();

        $totalBillsCount = Bill::count();


        /*
        |--------------------------------------------------------------------------
        | Pending Due Customers
        |--------------------------------------------------------------------------
        */

        $pendingCustomers = Customer::where(
            'balance_due',
            '>',
            0
        )
            ->orderByDesc('balance_due')
            ->limit(3)
            ->get();


        /*
        |--------------------------------------------------------------------------
        | Return Dashboard
        |--------------------------------------------------------------------------
        */

        return view('product.dashboard', compact(
            'todaysSales',
            'todaysBillCount',
            'totalDue',
            'totalCustomers',

            'monthlyTotals',
            'selectedYear',
            'availableYears',

            'cashTotal',
            'dueTotal',
            'cashPercent',
            'duePercent',

            'recentBills',
            'totalBillsCount',
            'pendingCustomers',

            'fromDate',
            'toDate',
            'isFiltered'
        ));
    }
}
